#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
#  ECom AI Dashboard V3.0 — 一键部署脚本 (Linux / macOS / Git Bash)
# ═══════════════════════════════════════════════════════════════════════════
#
# Usage:
#   bash deploy.sh setup      # 首次运行：安装依赖 + 配置
#   bash deploy.sh start      # 启动全部服务
#   bash deploy.sh stop       # 停止全部服务
#   bash deploy.sh status     # 查看服务状态
#   bash deploy.sh logs       # 查看日志
#
# What it does:
#   1. Auto-detects Python / Node.js / Docker
#   2. Creates venv, installs pip + npm dependencies
#   3. Generates .env config if missing
#   4. Starts Docker infra (optional) + 4 A2A microservices + backend + frontend
#   5. Shows service status dashboard
# ═══════════════════════════════════════════════════════════════════════════

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR"
BACKEND_DIR="$PROJECT_DIR/backend"
FRONTEND_DIR="$PROJECT_DIR/frontend"
VENV_DIR="$PROJECT_DIR/.venv"
LOG_DIR="$PROJECT_DIR/logs"
PID_DIR="$PROJECT_DIR/.pids"

# Colors
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'
CYAN='\033[0;36m'; BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'

log()    { echo -e "${CYAN}[INFO]${NC}  $1"; }
ok()     { echo -e "${GREEN}[OK]${NC}    $1"; }
warn()   { echo -e "${YELLOW}[WARN]${NC}  $1"; }
err()    { echo -e "${RED}[ERR]${NC}   $1"; }
header() { echo -e "\n${BOLD}${BLUE}$1${NC}\n"; }

mkdir -p "$LOG_DIR" "$PID_DIR"

# ═══════════════════════════════════════════════════════════════════════════
# Environment Detection
# ═══════════════════════════════════════════════════════════════════════════

check_prerequisites() {
    header "🔍 Checking Prerequisites..."

    local missing=0

    # Python 3.10+
    if command -v python3 &>/dev/null; then
        PYTHON=python3
    elif command -v python &>/dev/null; then
        PYTHON=python
    else
        err "Python 3.10+ not found. Install from https://python.org"
        missing=1
    fi

    if [ $missing -eq 0 ]; then
        local py_ver=$($PYTHON -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
        ok "Python $py_ver ($PYTHON)"
    fi

    # Node.js 18+
    if command -v node &>/dev/null; then
        local node_ver=$(node -v)
        ok "Node.js $node_ver"
    else
        warn "Node.js not found — frontend won't start. Install from https://nodejs.org"
    fi

    # Docker (optional)
    if command -v docker &>/dev/null && docker info &>/dev/null 2>&1; then
        ok "Docker available (PostgreSQL + Redis optional)"
        HAS_DOCKER=1
    else
        warn "Docker not available — app runs with built-in DataGenerator (no DB needed)"
        HAS_DOCKER=0
    fi

    # pip
    if $PYTHON -m pip --version &>/dev/null; then
        ok "pip ready"
    else
        err "pip not found"
        missing=1
    fi

    if [ $missing -eq 1 ]; then
        err "Missing required dependencies. Install them and re-run."
        exit 1
    fi

    echo ""
    return 0
}

# ═══════════════════════════════════════════════════════════════════════════
# Setup: install dependencies + generate config
# ═══════════════════════════════════════════════════════════════════════════

do_setup() {
    check_prerequisites

    header "📦 Setting up Python Virtual Environment..."

    if [ ! -d "$VENV_DIR" ]; then
        $PYTHON -m venv "$VENV_DIR"
        ok "Virtual environment created: $VENV_DIR"
    else
        ok "Virtual environment already exists"
    fi

    # Activate venv
    if [ -f "$VENV_DIR/Scripts/activate" ]; then
        source "$VENV_DIR/Scripts/activate"  # Windows Git Bash
    else
        source "$VENV_DIR/bin/activate"       # Linux / macOS
    fi

    header "📦 Installing Python Dependencies..."

    cd "$BACKEND_DIR"
    pip install --upgrade pip -q

    # Core deps (always needed)
    pip install fastapi uvicorn pydantic-settings loguru openai httpx \
        sse-starlette pyyaml sqlalchemy -q

    # Optional: Redis support
    pip install redis -q 2>/dev/null && ok "redis-py installed" || warn "redis-py skipped (Redis optional)"

    # Optional: PostgreSQL driver
    pip install asyncpg -q 2>/dev/null && ok "asyncpg installed" || warn "asyncpg skipped (PostgreSQL optional)"

    ok "Python dependencies installed"

    # Generate .env if missing
    if [ ! -f "$BACKEND_DIR/.env" ]; then
        header "⚙️  Generating default .env configuration..."
        cat > "$BACKEND_DIR/.env" << 'ENVEOF'
# ECom AI Dashboard V3.0 Configuration
# Generated by deploy.sh — edit as needed

DEBUG=true
APP_NAME="ECom AI Dashboard"
APP_VERSION=3.0.0

# Database (optional — app runs without it)
DATABASE_URL=postgresql+asyncpg://ecom:ecom2024@localhost:5432/ecom_dashboard

# Redis (optional — app runs without it)
REDIS_URL=redis://localhost:6379/0

# Secret key (change in production!)
SECRET_KEY=dev-secret-key-change-in-production-$(date +%s)

# Data source: auto (try Kafka → fallback to generator)
DATA_SOURCE=auto

# LLM (optional — Fast mode works without API key)
QWEN_API_KEY=
QWEN_MODEL=qwen-plus
QWEN_BASE_URL=https://dashscope.aliyuncs.com/compatible-mode/v1

# MCP Server
MCP_SERVER_ENABLED=true

# A2A Multi-Agent
A2A_ENABLED=true
A2A_TIMEOUT=3.0

# Agent Service URLs
DATA_AGENT_URL=http://localhost:8010
ANALYZE_AGENT_URL=http://localhost:8011
SENTIMENT_AGENT_URL=http://localhost:8012
REPORT_AGENT_URL=http://localhost:8013

# Guardrails
GUARDRAILS_ENABLED=true
MAX_AUTO_BUDGET_ADJUST_PCT=20.0

# CORS
CORS_ORIGINS=["http://localhost:5173","http://localhost:3000"]
ENVEOF
        ok ".env file created at $BACKEND_DIR/.env"
    else
        ok ".env already exists — skipping"
    fi

    # Frontend dependencies
    if command -v npm &>/dev/null; then
        header "📦 Installing Frontend Dependencies..."
        cd "$FRONTEND_DIR"
        if [ ! -d "node_modules" ]; then
            npm install --silent
            ok "npm dependencies installed"
        else
            ok "node_modules already exists"
        fi
    fi

    cd "$PROJECT_DIR"
    header "✅ Setup Complete!"
    echo ""
    echo "  Next step:  bash deploy.sh start"
    echo "  Then open:  http://localhost:5173"
    echo ""
}

# ═══════════════════════════════════════════════════════════════════════════
# Start all services
# ═══════════════════════════════════════════════════════════════════════════

do_start() {
    check_prerequisites

    # Activate venv
    if [ -f "$VENV_DIR/Scripts/activate" ]; then
        source "$VENV_DIR/Scripts/activate"
    elif [ -f "$VENV_DIR/bin/activate" ]; then
        source "$VENV_DIR/bin/activate"
    fi

    header "🚀 Starting ECom AI Dashboard V3.0..."

    # ── 0. Docker Infrastructure (optional) ────────────────────────
    if [ "$HAS_DOCKER" = "1" ]; then
        log "Starting Docker infrastructure..."
        cd "$PROJECT_DIR"
        docker compose up -d postgres redis 2>/dev/null || true
        sleep 2
    fi

    cd "$PROJECT_DIR"
    export PYTHONPATH="$BACKEND_DIR:$PYTHONPATH"

    # ── 1. A2A Microservices ──────────────────────────────────────
    log "Starting A2A Agent microservices..."

    nohup uvicorn microservices.data-agent.main:app \
        --host 0.0.0.0 --port 8010 \
        > "$LOG_DIR/data-agent.log" 2>&1 &
    echo $! > "$PID_DIR/data-agent.pid"

    nohup uvicorn microservices.analyze-agent.main:app \
        --host 0.0.0.0 --port 8011 \
        > "$LOG_DIR/analyze-agent.log" 2>&1 &
    echo $! > "$PID_DIR/analyze-agent.pid"

    nohup uvicorn microservices.sentiment-agent.main:app \
        --host 0.0.0.0 --port 8012 \
        > "$LOG_DIR/sentiment-agent.log" 2>&1 &
    echo $! > "$PID_DIR/sentiment-agent.pid"

    nohup uvicorn microservices.report-agent.main:app \
        --host 0.0.0.0 --port 8013 \
        > "$LOG_DIR/report-agent.log" 2>&1 &
    echo $! > "$PID_DIR/report-agent.pid"

    sleep 2
    ok "Microservices starting on ports 8010-8013"

    # ── 2. Main Backend ───────────────────────────────────────────
    log "Starting main backend..."
    cd "$BACKEND_DIR"
    nohup uvicorn app.main:app \
        --host 0.0.0.0 --port 8001 \
        > "$LOG_DIR/backend.log" 2>&1 &
    echo $! > "$PID_DIR/backend.pid"
    sleep 3
    ok "Backend starting on port 8001"

    # ── 3. Frontend ───────────────────────────────────────────────
    if command -v npm &>/dev/null; then
        log "Starting frontend..."
        cd "$FRONTEND_DIR"
        nohup npm run dev > "$LOG_DIR/frontend.log" 2>&1 &
        echo $! > "$PID_DIR/frontend.pid"
        sleep 2
        ok "Frontend starting on port 5173"
    else
        warn "npm not found — skipping frontend"
    fi

    # ── 4. Show Dashboard ─────────────────────────────────────────
    sleep 3
    do_status

    echo ""
    echo -e "  ${GREEN}Frontend :${NC}  http://localhost:5173"
    echo -e "  ${GREEN}Backend  :${NC}  http://localhost:8001"
    echo -e "  ${GREEN}API Docs :${NC}  http://localhost:8001/docs"
    echo -e "  ${GREEN}Insights :${NC}  http://localhost:5173/insights"
    echo ""
    echo -e "  Stop:      ${YELLOW}bash deploy.sh stop${NC}"
    echo -e "  Logs:      ${YELLOW}bash deploy.sh logs${NC}"
    echo ""
}

# ═══════════════════════════════════════════════════════════════════════════
# Stop all services
# ═══════════════════════════════════════════════════════════════════════════

do_stop() {
    header "🛑 Stopping all services..."

    for name in frontend backend data-agent analyze-agent sentiment-agent report-agent; do
        local pidfile="$PID_DIR/$name.pid"
        if [ -f "$pidfile" ]; then
            local pid=$(cat "$pidfile")
            if kill -0 "$pid" 2>/dev/null; then
                kill "$pid" 2>/dev/null && ok "Stopped $name (PID $pid)" || true
            fi
            rm -f "$pidfile"
        fi
    done

    # Force kill any remaining uvicorn processes
    pkill -f "uvicorn.*app.main" 2>/dev/null || true
    pkill -f "uvicorn.*microservices" 2>/dev/null || true

    ok "All services stopped"
}

# ═══════════════════════════════════════════════════════════════════════════
# Status dashboard
# ═══════════════════════════════════════════════════════════════════════════

do_status() {
    header "📊 Service Status"

    check_port() {
        local port=$1
        local name=$2
        if curl -s "http://localhost:$port/health" &>/dev/null; then
            local info=$(curl -s "http://localhost:$port/health" 2>/dev/null)
            echo -e "  ${GREEN}✅${NC} $name (:$port) — $info"
        else
            echo -e "  ${RED}❌${NC} $name (:$port) — not running"
        fi
    }

    check_port 8001 "Backend       "
    check_port 8010 "DataAgent     "
    check_port 8011 "AnalyzeAgent  "
    check_port 8012 "SentimentAgent"
    check_port 8013 "ReportAgent   "

    if curl -s http://localhost:5173 &>/dev/null; then
        echo -e "  ${GREEN}✅${NC} Frontend      (:5173) — Vue 3 Dev Server"
    else
        echo -e "  ${YELLOW}⚠️${NC}  Frontend      (:5173) — not running"
    fi
}

# ═══════════════════════════════════════════════════════════════════════════
# Logs
# ═══════════════════════════════════════════════════════════════════════════

do_logs() {
    local svc="${1:-all}"
    header "📋 Service Logs"

    tail_log() {
        local name=$1; local file="$LOG_DIR/$name.log"
        if [ -f "$file" ]; then
            echo -e "${BOLD}─── $name ───${NC}"
            tail -20 "$file"
            echo ""
        fi
    }

    case "$svc" in
        all)
            for log in backend data-agent analyze-agent sentiment-agent report-agent frontend; do
                [ -f "$LOG_DIR/$log.log" ] && tail_log "$log"
            done
            ;;
        backend|data-agent|analyze-agent|sentiment-agent|report-agent|frontend)
            tail_log "$svc"
            ;;
        *)
            echo "Usage: bash deploy.sh logs [service-name]"
            echo "  services: backend, data-agent, analyze-agent, sentiment-agent, report-agent, frontend, all"
            ;;
    esac
}

# ═══════════════════════════════════════════════════════════════════════════
# Main dispatch
# ═══════════════════════════════════════════════════════════════════════════

case "${1:-start}" in
    setup)   do_setup ;;
    start)   do_start ;;
    stop)    do_stop ;;
    status)  do_status ;;
    logs)    do_logs "${2:-all}" ;;
    restart) do_stop; sleep 2; do_start ;;
    *)
        echo "Usage: bash deploy.sh {setup|start|stop|restart|status|logs}"
        echo ""
        echo "  setup    — First run: install dependencies + create .env"
        echo "  start    — Start all services (infra + microservices + backend + frontend)"
        echo "  stop     — Stop all services"
        echo "  restart  — Stop then start"
        echo "  status   — Show service health dashboard"
        echo "  logs     — View service logs"
        echo ""
        echo "  After starting, open: http://localhost:5173"
        ;;
esac
