"""Ad Executor MCP tool — V3.0 后链路执行 (Guardrails).

This tool represents the "action" capability — Agent can propose
budget adjustments, but execution goes through safety guardrails:

  1. Agent generates ExecutionProposal (never calls API directly)
  2. Budget change < 20% → auto-execute
  3. Budget change >= 20% → manual approval required (Feishu card)
  4. Pre-execution snapshot saved to Redis for rollback
  5. Post-execution ROAS check after 30 min
"""

import json
import time
from dataclasses import dataclass, field

from loguru import logger

from app.mcp.registry import BaseMCPTool, MCPRegistry
from app.mcp.tools.context import get_context
from app.core.config import get_settings

TOOLS = []
settings = get_settings()


@dataclass
class ExecutionProposal:
    """A proposal generated by the Agent for human/auto approval."""
    action: str                # "adjust_budget" | "pause_campaign" | "transfer_budget"
    channel: str               # e.g. "拼多多", "抖音"
    campaign_id: str           # ad campaign identifier
    current_budget: float
    proposed_budget: float
    change_pct: float
    reason: str
    risk_level: str = "low"    # low | medium | high
    status: str = "pending"    # pending | auto_approved | manual_required | executed | rejected
    snapshot_key: str = ""
    created_at: float = field(default_factory=time.time)


# In-memory proposal store (in production: PostgreSQL)
_proposals: list[ExecutionProposal] = []


async def _execute_ad_action(params: dict) -> dict:
    """Execute an advertising action through the guardrails system.

    This is the V3.0 key differentiator: Agent can act, not just observe.
    """
    action = params.get("action", "adjust_budget")
    channel = params.get("channel", "")
    campaign_id = params.get("campaign_id", "unknown")
    current_budget = float(params.get("current_budget", 0))
    proposed_budget = float(params.get("proposed_budget", 0))

    if current_budget <= 0:
        return {"error": "Invalid current_budget"}

    change_pct = (proposed_budget - current_budget) / current_budget * 100

    # Build proposal
    proposal = ExecutionProposal(
        action=action,
        channel=channel,
        campaign_id=campaign_id,
        current_budget=current_budget,
        proposed_budget=proposed_budget,
        change_pct=round(change_pct, 1),
        reason=params.get("reason", ""),
    )

    # ── Guardrail 1: Budget change within safe threshold? ──────────
    if abs(change_pct) <= settings.MAX_AUTO_BUDGET_ADJUST_PCT:
        proposal.status = "auto_approved"
        proposal.risk_level = "low"
        logger.info(f"Ad Executor: auto-approved {channel}/{campaign_id} ({change_pct:+.1f}%)")
    else:
        proposal.status = "manual_required"
        proposal.risk_level = "high" if abs(change_pct) > 50 else "medium"
        logger.info(
            f"Ad Executor: manual approval required for {channel}/{campaign_id} "
            f"({change_pct:+.1f}% > {settings.MAX_AUTO_BUDGET_ADJUST_PCT}% threshold)"
        )

    # ── Guardrail 2: Save pre-execution snapshot ────────────────────
    snapshot_key = f"budget:snapshot:{channel}:{campaign_id}:{int(time.time())}"
    proposal.snapshot_key = snapshot_key

    _gen, _streams, _store = get_context()
    # Save snapshot to Redis via CacheManager if available
    try:
        from app.services.cache_manager import get_cache
        cache = get_cache()
        await cache.set(snapshot_key, {
            "channel": channel,
            "campaign_id": campaign_id,
            "budget_before": current_budget,
            "timestamp": time.time(),
        }, ttl=3600)
    except Exception as e:
        logger.warning(f"Ad Executor: snapshot save failed: {e}")

    # Store proposal
    _proposals.append(proposal)

    return {
        "proposal_id": str(len(_proposals)),
        "action": action,
        "channel": channel,
        "campaign_id": campaign_id,
        "change_pct": round(change_pct, 1),
        "status": proposal.status,
        "risk_level": proposal.risk_level,
        "snapshot_key": snapshot_key,
        "message": (
            f"预算调整已{'自动批准' if proposal.status == 'auto_approved' else '提交人工审批'}"
            f"：{channel} {campaign_id} {change_pct:+.1f}%"
        ),
    }


async def _list_proposals(params: dict) -> dict:
    """List all execution proposals (for admin review)."""
    status_filter = params.get("status", "")
    result = []
    for p in _proposals:
        if status_filter and p.status != status_filter:
            continue
        result.append({
            "action": p.action,
            "channel": p.channel,
            "campaign_id": p.campaign_id,
            "change_pct": p.change_pct,
            "status": p.status,
            "risk_level": p.risk_level,
            "reason": p.reason,
        })
    return {"proposals": result, "total": len(result)}


async def _approve_proposal(params: dict) -> dict:
    """Manually approve a pending proposal."""
    proposal_id = int(params.get("proposal_id", 0)) - 1
    if 0 <= proposal_id < len(_proposals):
        p = _proposals[proposal_id]
        if p.status == "manual_required":
            p.status = "executed"
            logger.info(f"Ad Executor: manually approved proposal #{proposal_id + 1}")
            return {"status": "executed", "message": f"已执行: {p.channel} {p.change_pct:+.1f}%"}
    return {"error": "Proposal not found or not pending approval"}


TOOLS.append(BaseMCPTool(
    name="execute_ad_action",
    description="执行广告操作：调整预算、暂停广告组、转移预算。含安全护栏（阈值检查+人工审批）。",
    parameters={
        "type": "object",
        "properties": {
            "action": {"type": "string", "enum": ["adjust_budget", "pause_campaign", "transfer_budget"], "description": "操作类型"},
            "channel": {"type": "string", "description": "渠道：淘宝/京东/拼多多/抖音"},
            "campaign_id": {"type": "string", "description": "广告组ID"},
            "current_budget": {"type": "number", "description": "当前日预算"},
            "proposed_budget": {"type": "number", "description": "建议日预算"},
            "reason": {"type": "string", "description": "调整原因"},
        },
        "required": ["action", "channel", "current_budget", "proposed_budget"],
    },
    category="action",
    tags=["广告", "预算", "执行", "护栏"],
    handler=_execute_ad_action,
))

TOOLS.append(BaseMCPTool(
    name="list_ad_proposals",
    description="列出所有广告执行提案（用于审批管理）。",
    parameters={
        "type": "object",
        "properties": {
            "status": {"type": "string", "description": "按状态筛选：pending/auto_approved/manual_required/executed"},
        },
        "required": [],
    },
    category="action",
    tags=["广告", "审批", "提案"],
    handler=_list_proposals,
))

TOOLS.append(BaseMCPTool(
    name="approve_ad_proposal",
    description="手动审批广告执行提案。",
    parameters={
        "type": "object",
        "properties": {
            "proposal_id": {"type": "string", "description": "提案ID"},
        },
        "required": ["proposal_id"],
    },
    category="action",
    tags=["广告", "审批"],
    handler=_approve_proposal,
))

for t in TOOLS:
    MCPRegistry.register(t)
